error: Error capturado en el errorHandler:  getAllPets no encontro mascotas en la base de datos {"stack":"Error: getAllPets no encontro mascotas en la base de datos\n    at getAllPets (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:11:19)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","timestamp":"2025-05-30T13:23:45.358Z"}
error: Error capturado en el errorHandler:  Pets validation failed: birthDate: Cast to date failed for value "formato no valido seguramente" (type string) at path "birthDate" {"_message":"Pets validation failed","errors":{"birthDate":{"kind":"date","message":"Cast to date failed for value \"formato no valido seguramente\" (type string) at path \"birthDate\"","name":"CastError","path":"birthDate","reason":{"actual":false,"code":"ERR_ASSERTION","expected":true,"generatedMessage":true,"operator":"=="},"stringValue":"\"formato no valido seguramente\"","value":"formato no valido seguramente","valueType":"string"}},"stack":"ValidationError: Pets validation failed: birthDate: Cast to date failed for value \"formato no valido seguramente\" (type string) at path \"birthDate\"\n    at Document.invalidate (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\mongoose\\lib\\document.js:3123:32)\n    at model.$set (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\mongoose\\lib\\document.js:1463:12)\n    at model.$set (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\mongoose\\lib\\document.js:1146:16)\n    at model.Document (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\mongoose\\lib\\document.js:166:12)\n    at model.Model (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\mongoose\\lib\\model.js:121:12)\n    at new model (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\mongoose\\lib\\model.js:5038:15)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\mongoose\\lib\\model.js:3187:22\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\mongoose\\lib\\model.js:3222:7\n    at Array.forEach (<anonymous>)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\mongoose\\lib\\model.js:3221:15","timestamp":"2025-05-30T13:31:36.921Z"}
error: Error capturado en el errorHandler:  INVALID_PARAM {"stack":"Error: INVALID_PARAM\n    at createPet (file:///C:/Users/Asus/Desktop/ADOPTME/src/controllers/pets.controller.js:26:19)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:144:13)\n    at Route.dispatch (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\route.js:114:3)\n    at Layer.handle [as handle_request] (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:175:3)\n    at router (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\express\\lib\\router\\index.js:47:12)","timestamp":"2025-05-30T13:35:41.140Z"}
error: Error capturado en el errorHandler:  Unexpected token ',', ..."  "name": ,
    "sp"... is not valid JSON {"body":"{\r\n    \"name\": ,\r\n    \"specie\": \"mezcla de collie con bestia\",\r\n    \"birthDate\": \"1990-05-30\"\r\n}","expose":true,"stack":"SyntaxError: Unexpected token ',', ...\"  \"name\": ,\r\n    \"sp\"... is not valid JSON\n    at JSON.parse (<anonymous>)\n    at parse (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\body-parser\\lib\\types\\json.js:89:19)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\body-parser\\lib\\read.js:128:18\n    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)\n    at invokeCallback (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\raw-body\\index.js:231:16)\n    at done (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\raw-body\\index.js:220:7)\n    at IncomingMessage.onEnd (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\raw-body\\index.js:280:7)\n    at IncomingMessage.emit (node:events:518:28)\n    at endReadableNT (node:internal/streams/readable:1696:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","status":400,"statusCode":400,"timestamp":"2025-05-30T13:36:10.933Z","type":"entity.parse.failed"}
error: Error capturado en el errorHandler:  Expected ',' or '}' after property value in JSON at position 29 {"body":"{\r\n    \"name\": \r\n    \"specie\": \"mezcla de collie con bestia\",\r\n    \"birthDate\": \"1990-05-30\"\r\n}","expose":true,"stack":"SyntaxError: Expected ',' or '}' after property value in JSON at position 29\n    at JSON.parse (<anonymous>)\n    at parse (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\body-parser\\lib\\types\\json.js:89:19)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\body-parser\\lib\\read.js:128:18\n    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)\n    at invokeCallback (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\raw-body\\index.js:231:16)\n    at done (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\raw-body\\index.js:220:7)\n    at IncomingMessage.onEnd (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\raw-body\\index.js:280:7)\n    at IncomingMessage.emit (node:events:518:28)\n    at endReadableNT (node:internal/streams/readable:1696:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","status":400,"statusCode":400,"timestamp":"2025-05-30T13:36:26.197Z","type":"entity.parse.failed"}
error: Error capturado en el errorHandler:  Unexpected token 'i', ..."  "name": ipa,
    "... is not valid JSON {"body":"{\r\n    \"name\": ipa,\r\n    \"specie\": \"mezcla de collie con bestia\",\r\n    \"birthDate\": \"1990-05-30\"\r\n}","expose":true,"stack":"SyntaxError: Unexpected token 'i', ...\"  \"name\": ipa,\r\n    \"... is not valid JSON\n    at JSON.parse (<anonymous>)\n    at parse (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\body-parser\\lib\\types\\json.js:89:19)\n    at C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\body-parser\\lib\\read.js:128:18\n    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)\n    at invokeCallback (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\raw-body\\index.js:231:16)\n    at done (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\raw-body\\index.js:220:7)\n    at IncomingMessage.onEnd (C:\\Users\\Asus\\Desktop\\ADOPTME\\node_modules\\raw-body\\index.js:280:7)\n    at IncomingMessage.emit (node:events:518:28)\n    at endReadableNT (node:internal/streams/readable:1696:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","status":400,"statusCode":400,"timestamp":"2025-05-30T13:36:35.858Z","type":"entity.parse.failed"}
